package com.example.workspace.common.api;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "API 错误码")
public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    CONFLICT,
    VERSION_CONFLICT,
    BUSINESS_RULE_VIOLATION,
    AUTH_INVALID_CREDENTIALS,
    AUTH_EMAIL_ALREADY_EXISTS,
    AUTH_ACCOUNT_DISABLED,
    AUTH_TOKEN_EXPIRED,
    AUTH_TOKEN_INVALID,
    AUTH_REFRESH_TOKEN_INVALID,
    RATE_LIMITED,
    TAG_VERSION_CONFLICT,
    TAG_NAME_CONFLICT,
    PROJECT_ARCHIVED,
    RESOURCE_READ_ONLY,
    FILE_SCOPE_CONFLICT,
    FILE_HAS_REFERENCES,
    UPLOAD_STATE_CONFLICT,
    IDEMPOTENCY_CONFLICT,
    STORAGE_QUOTA_EXCEEDED,
    FILE_TOO_LARGE,
    FILE_TYPE_NOT_ALLOWED,
    FILE_STORAGE_UNAVAILABLE,
    FILE_CONTENT_UNAVAILABLE,
    FILE_INTEGRITY_CHECK_FAILED,
    SEARCH_QUERY_INVALID,
    SEARCH_UNAVAILABLE,
    INTERNAL_ERROR
}
