import { expect, test } from '@playwright/test'

import { mockAuthApi } from './mock-auth'

test('Rive and the workspace respond to focus, errors, submission and dashboard entry', async ({ page }) => {
  await mockAuthApi(page)
  await page.goto('/login')
  const scene = page.locator('.auth-shell')
  const robot = page.locator('.workspace-mascot')
  await expect(robot).toHaveAttribute('data-renderer', 'rive')
  await page.getByLabel('邮箱', { exact: true }).click()
  await expect(scene).toHaveAttribute('data-auth-state', 'email-focus')
  await expect(robot).toHaveAttribute('data-machine-state', /email/)
  await page.getByLabel('密码', { exact: true }).click()
  await expect(scene).toHaveAttribute('data-auth-state', 'password-focus')
  await expect(robot).toHaveAttribute('data-machine-state', /password/)
  await page.getByRole('button', { name: '进入工作空间', exact: true }).click()
  await expect(scene).toHaveAttribute('data-auth-state', 'error')
  await expect(page.getByText('请输入有效邮箱', { exact: true })).toBeVisible()
  await expect(page.getByText('请输入密码', { exact: true })).toBeVisible()
  await page.getByLabel('邮箱', { exact: true }).fill('preview@example.com')
  await page.getByLabel('密码', { exact: true }).fill('LocalPreview123')
  await page.getByRole('button', { name: '显示密码', exact: true }).click()
  await expect(page.getByLabel('密码', { exact: true })).toHaveAttribute('type', 'text')
  await page.getByRole('button', { name: '进入工作空间', exact: true }).click()
  await expect(scene).toHaveAttribute('data-auth-state', /submitting|success/)
  await expect(scene).toHaveAttribute('data-auth-state', 'success')
  await expect(robot).toHaveAttribute('data-machine-state', /success/)
  await expect(page).toHaveURL(/\/app\/dashboard$/)
  expect(await page.evaluate(() => Object.values(localStorage).some(value => value.includes('LocalPreview123')))).toBe(false)
})

test('register crossfades, validates confirmation and completes the local flow', async ({ page }) => {
  await mockAuthApi(page)
  await page.goto('/login')
  await page.getByRole('link', { name: '创建工作空间', exact: true }).click()
  await expect(page).toHaveURL(/\/register$/)
  await expect(page.getByRole('heading', { name: '创建工作空间', exact: true })).toBeVisible()
  await expect(page.locator('.auth-shell')).toHaveAttribute('data-auth-state', 'register')
  await page.getByLabel('昵称', { exact: true }).fill('体验用户')
  await page.getByLabel('邮箱', { exact: true }).fill('preview@example.com')
  await page.getByLabel('密码', { exact: true }).fill('Preview1234')
  await page.getByLabel('确认密码', { exact: true }).fill('Mismatch123')
  await page.getByRole('button', { name: '创建并进入工作空间' }).click()
  await expect(page.getByText('两次输入的密码不一致')).toBeVisible()
  await page.getByLabel('确认密码', { exact: true }).fill('Preview1234')
  await page.getByRole('button', { name: '创建并进入工作空间' }).click()
  await expect(page).toHaveURL(/\/app\/dashboard$/)
})

for (const width of [1920, 1440, 1100, 768, 390, 320]) {
  test(`responsive scene at ${width}px retains the robot and usable forms`, async ({ page }) => {
    await mockAuthApi(page)
    await page.setViewportSize({ width, height: 941 })
    await page.goto('/login')
    await expect(page.locator('.workspace-mascot')).toHaveAttribute('data-renderer', 'rive')
    await expect(page.locator('.auth-shell')).toHaveCSS('opacity', '1')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await expect(page.getByLabel('邮箱', { exact: true })).toBeVisible()
    if (width < 1024)
      await expect(page.locator('.workspace-card-tasks')).toBeHidden()
    await page.screenshot({ path: `.artifacts/login-${width}.png`, fullPage: true })
    await page.goto('/register')
    await expect(page.getByLabel('确认密码', { exact: true })).toBeVisible()
    await expect(page.locator('.auth-shell')).toHaveCSS('opacity', '1')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `.artifacts/register-${width}.png`, fullPage: true })
  })
}

test('reduced motion stops continuous effects while keeping focus and success feedback', async ({ page }) => {
  await mockAuthApi(page)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/login')
  await expect(page.locator('.auth-shell')).toHaveAttribute('data-motion', 'reduced')
  await expect(page.locator('.workspace-mascot')).toHaveAttribute('data-machine-state', /rest/)
  expect(await page.locator('.orbit-flow').first().evaluate(element => getComputedStyle(element).animationName)).toBe('none')
  await page.getByLabel('邮箱', { exact: true }).fill('preview@example.com')
  await expect(page.locator('.auth-shell')).toHaveAttribute('data-auth-state', 'email-focus')
  await page.getByLabel('密码', { exact: true }).fill('LocalPreview123')
  await page.getByRole('button', { name: '进入工作空间', exact: true }).click()
  await expect(page).toHaveURL(/\/app\/dashboard$/)
})

test('Rive load failure preserves the robot and working forms', async ({ page }) => {
  await mockAuthApi(page)
  await page.route('**/workspace-companion.riv', route => route.abort())
  await page.goto('/login')
  await expect(page.locator('.workspace-mascot')).toHaveAttribute('data-renderer', 'svg')
  await expect(page.locator('.mascot-fallback')).toBeVisible()
  await page.getByLabel('邮箱', { exact: true }).fill('preview@example.com')
  await page.getByLabel('密码', { exact: true }).fill('LocalPreview123')
  await page.getByRole('button', { name: '进入工作空间', exact: true }).click()
  await expect(page).toHaveURL(/\/app\/dashboard$/)
})
