package com.example.workspace.common.api;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    CONFLICT,
    BUSINESS_RULE_VIOLATION,
    AUTH_INVALID_CREDENTIALS,
    AUTH_EMAIL_ALREADY_EXISTS,
    AUTH_ACCOUNT_DISABLED,
    AUTH_TOKEN_EXPIRED,
    AUTH_TOKEN_INVALID,
    AUTH_REFRESH_TOKEN_INVALID,
    RATE_LIMITED,
    INTERNAL_ERROR
}
